const ARTICLES = [
  ["$50 Million Crypto Lost in Seconds: Anyone Can Copy-Paste","50-million-crypto-lost-seconds-copy-paste"],
  ["Ark Invest Sees One-Third of Bitcoin Supply at Risk From Quantum Threat","-j91qefex"],
  ["Bhutan Is Quietly Selling Its Bitcoin And Nobody Knows Why","bhutan-quietly-selling-bitcoin-nobody-knows-why"],
  ["Bitcoin Buyers Show 'Renewed Conviction' with BTC Price Push Above $79K","bitcoin-buyers-renewed-conviction-btc-price-push-79k"],
  ["Bitcoin Didn’t Wait. Ceasefire Headlines Were Enough","bitcoin-didnt-wait-ceasefire-headlines-were-enough"],
  ["Bitcoin ETFs Add $251M as Goldman Sachs Tops XRP ETF Holders","bitcoin-etfs-gain-251m-goldman-sachs-leads-xrp-etf-holders"],
  ["Bitcoin ETFs Bounce $562M After $1.5B Sell-Off: Building DeFi Portfolios That Survive Volatility","bitcoin-etfs-bounce-selloff-defi-portfolios-volatility"],
  ["Bitdeer Sells Entire 943 BTC Treasury: Largest Hashrate Miner Drops to Zero Holdings","bitdeer-sells-943-btc-treasury-miner-zero-holdings"],
  ["China Turns Up the Heat: What Beijing's New Online Marketing Rules Actually Mean for Crypto","china-beijing-marketing-rules-crypto"],
  ["Crypto Liquidations Hit $2.5B+: Lessons from the Weekend Wipeout and What Comes Next","crypto-liquidations-2-5b-lessons-weekend-wipeout"],
  ["Crypto PAC's Texas Ad Pause Signals a Shift in Political Strategy","crypto-pacs-texas-ad-pause-signals-shift-political-strategy"],
  ["Crypto PACs Gear Up for 2026 Midterms: Influence Meets Political Risk","crypto-pacs-gear-up-2026-midterms-influence-risk"],
  ["CZ's Message to Anyone Hitting Rock Bottom: 'Keep Walking' — And He's Speaking From Experience","cz-message-rock-bottom-keep-walking-experience"],
  ["CZ's Supercycle Call: When Regulators Stop Hunting Crypto","czs-supercycle-call-regulators-stop-hunting-crypto"],
  ["DAOs Aren't Doomed, They Just Need to Evolve: Aave Founder","daos-not-doomed-evolve-aave-founder"],
  ["DeFAI's Breakthrough: How AI Agents Are Quietly Fixing Crypto's Biggest Problem","defai-breakthrough-ai-agents-fixing-crypto-problem"],
  ["Dubai Launches Secondary Trading for Tokenized Property; Trump-Linked WLFI Tokenizes Maldives Resort","dubai-tokenized-property-trading-wlfi-maldives-resort"],
  ["Dutch Regulator Bans Polymarket, Hits Crypto Prediction Platform with Up to €840K Fines","dutch-regulator-fines-polymarket-crypto-840k"],
  ["ETH Valuation Metric Hits Level Not Seen Since 2022: Is a Rally to $2.5K Next?","eth-valuation-metric-hits-2022-level-rally-2-5k"],
  ["Ethereum Price Prediction 2026: Will ETH Hit New All-Time Highs This Year?","ethereum-price-prediction-2026-eth-ath"],
  ["Ethereum's Quiet Upgrade: When Infrastructure Actually Improves","ethereum-quiet-upgrade-infrastructure-improves"],
  ["Fake Crypto Wallets Designed to Drain Digital Assets Identified on Apple App Store","fake-crypto-wallets-drain-digital-assets-apple-app-store"],
  ["FDIC Chair Says No Deposit Insurance for Stablecoins Under GENIUS Act","fdic-chair-no-deposit-insurance-stablecoins-genius-act"],
  ["From Bitcoin to AI: MARA's $168M Exaion Acquisition Signals Mining's Evolution","mara-exaion-acquisition-bitcoin-ai-mining-evolution"],
  ["From Hype to Maturity: 2026 Crypto Trends That Will Outlast the Crash","hype-maturity-2026-crypto-trends-outlast-crash"],
  ["Higher CPI Print for March Already 'Baked In' to BTC Price — Analysts","higher-cpi-print-march-already-baked-btc-price-analysts"],
  ["Hong Kong Just Licensed Its First HKD Stablecoins — And the Banks Are Running the Show","hong-kong-licenses-hkd-stablecoins-banks-lead"],
  ["Hong Kong's Stablecoin Licenses: Why 'Very Few' Approvals in March Matters More Than the Count","hong-kong-stablecoin-licenses-few-approvals-march-matters"],
  ["How Social Engineering Turned “Unhackable” Crypto Security into a $282M Loss","social-engineering-unhackable-crypto-security-282m-loss"],
  ["India Arrests Darwin Labs Co-Founder in GainBitcoin Scam Probe","india-arrests-darwin-labs-co-founder-gainbitcoin-scam"],
  ["Japan Just Reclassified Crypto as a Financial Instrument: Here's What Actually Changes","japan-reclassified-crypto-financial-instrument-changes"],
  ["Kiyosaki Says Buy Bitcoin and Gold. The '74 Shift Isn't Done.","kiyosaki-buy-bitcoin-and-gold-74-shift"],
  ["Malaysia's $1.1 Billion Bitcoin Mining Crisis: When Crypto Threatens National Infrastructure",""],
  ["Mastercard Launches Crypto Partner Program With a 'Who's Who' of Industry","mastercard-crypto-partner-program-whos-who-industry"],
  ["Metaplanet Raises $50 Million in Zero-Interest Bonds to Buy More Bitcoin","metaplanet-buy-bitcoin-50m-bonds"],
  ["MicroStrategy Didn’t Blink. It Repositioned.","microstrategy-didnt-blink-repositioned"],
  ["Philippines SEC Flags dYdX and Six Crypto Platforms as Unauthorized","philippines-sec-flags-dydx-six-crypto-platforms-unauthorized"],
  ["Rand on a Leash: South Africa Wants to Track Every Crypto Move You Make Across Its Borders","rand-on-leash-south-africa-track-crypto-move-borders"],
  ["Ripple to Buy Back $750M in Shares Through April: What's Actually Going On","ripple-buy-back-750m-shares-through-april-what-going-on"],
  ["Ripple's UK Breakthrough: When Cross-Border Crypto Payments Get Regulatory Approval","ripple-uk-breakthrough-cross-border-crypto-payments-approval"],
  ["RISCOIN's Philippine Recruitment Drive: A Growing Concern That Regulators Are Now Taking Seriously","riscoin-philippine-recruitment-drive-regulators-concern"],
  ["Satoshi-Era Whale Dumps $1.3 Billion in Bitcoin After 14 Years: What He Knows That You Don't","satoshi-era-whale-dumps-1-3-billion-bitcoin-14-years"],
  ["Scammers Demand Crypto from Stranded Ships in the Strait of Hormuz","scammers-demand-crypto-stranded-ships-strait-of-hormuz"],
  ["SCOTUS Voids Trump Tariffs: 10% Global Levy Directly Fuels Bitcoin Volatility & Inflation Hedge Surge","scotus-voids-trump-tariffs-bitcoin-volatility-inflation"],
  ["September 2026: The Deadline That Could Kill Your UK Crypto Business","september-2026-deadline-kill-uk-crypto-business"],
  ["Singapore Just Made Cross-Border Payments Less Painful: Here's Why It Matters","singapore-cross-border-payments-why-it-matters"],
  ["South Korea's Bitcoin Seizure Ruling: Why $33 Billion in Crypto Just Lost Its Legal Shield","south-korea-bitcoin-seizure-ruling-33-billion-legal-shield"],
  ["South Korea's Tax Agency Opens Bidding for Crypto Tracing Tool","south-koreas-tax-agency-opens-bidding-crypto-tracing-tool"],
  ["South Korean Prosecutors Recover $21.4M Stolen Bitcoin as Hacker Returns 320 BTC","south-korea-hacker-returns-bitcoin"],
  ["Sovereign Gold on Blockchain: Bhutan's TER Signals the Next Crypto Adoption Wave","sovereign-gold-blockchain-bhutan-ter-crypto-adoption-wave"],
  ["Tether’s $544M Turkey Freeze: Stablecoins as State Enforcement Tools","tether-544m-turkey-freeze-stablecoins-enforcement"],
  ["The $150,000 Question: Why Bitcoin’s December Range Still Matters","150000-question-bitcoin-december-range-matters"],
  ["The $657 Million Flood: Why Your Crypto Portfolio Might Wake Up to a Nasty Surprise This Week","657-million-flood-crypto-portfolio-nasty-surprise"],
  ["The Crypto Phone Is at It Again: Solana Mobile’s $SKR Bet","crypto-phone-solana-mobile-skr-bet"],
  ["The End of Crypto Tax Anonymity: 48 Countries Just Flipped the Switch","end-crypto-tax-anonymity-48-countries-flipped-switch"],
  ["The High Priests Problem: Why Ethereum’s Complexity Is Its Real Existential Threat","high-priests-problem-ethereum-complexity-threat"],
  ["The Phishing Attack That Bypassed Everything: DeFi's Real Security Problem","phishing-attack-bypassed-everything-defi-security-problem"],
  ["The Tokenization Supercycle: When Wall Street Puts Real Assets On-Chain","tokenization-supercycle-wall-street-real-assets-on-chain"],
  ["Tokenization Supercycle Incoming: Why 2026 Could Still Be Huge Despite the Dip","tokenization-supercycle-incoming-why-2026-huge-dip"],
  ["Tokenized Assets Climb to $23.6B as Investors Seek Always-On Markets","tokenized-assets-climb-23-6b-investors-seek-always-on-markets"],
  ["Treasury Secretary Bessent Rules Out Bitcoin Bailout: No Authority for Government Intervention","treasury-secretary-bessent-rules-out-bitcoin-bailout"],
  ["Trump-Linked American Bitcoin Energizes 11,298 New ASICs","trump-linked-american-bitcoin-energizes-11298-new-asics"],
  ["Trump-Iran Deadline Chaos Breaks Markets, Crypto Rises Anyway","trump-iran-deadline-chaos-breaks-markets-crypto-rises-anyway"],
  ["Trump's 2025 Crypto Revolution: From Campaign Promises to Federal Law","trump-2025-crypto-revolution-campaign-promises-federal-law"],
  ["US Seeks Forfeiture of $3.4M in USDT Tied to Crypto Investment Scam","us-seeks-forfeiture-34m-usdt-tied-crypto-investment-scam"],
  ["Uzbekistan Creates State-Backed Crypto Mining Zone with Tax Breaks","uzbekistan-state-backed-crypto-mining-zone-tax-breaks"],
  ["Venezuela's $60 Billion Bitcoin Bombshell: The Geopolitical Catalyst Crypto Needed","venezuela-60-billion-bitcoin-geopolitical-crypto"],
  ["Vitalik: Ethereum Solved Crypto's Impossible Problem","vitalik-ethereum-solved-cryptos-impossible-problem"],
  ["Wall Street Builds Infrastructure Which Crypto Touted","wall-street-builds-infrastructure-crypto-touted"],
  ["Wall Street's Crypto Endgame: When the Holdouts Finally Cave","wall-street-crypto-endgame-holdouts-finally-cave"],
  ["Warsh Nomination Triggers $250B Crypto Wipeout — Bitcoin Down 17%, Fed Independence at Risk","warsh-250b-crypto-wipeout-bitcoin-17-fed-risk"],
  ["When $11 Trillion Blinks: Vanguard’s Quiet Surrender to Crypto","11-trillion-bursts-blink-vanguard-surrender-crypto"],
  ["When AI Romance Scams Hit Crypto: Hong Kong’s $46 Million Wake-Up Call","ai-romance-crypto-fraud-hong-kong-46m-wake-up-call"],
  ["When Digital Dollars Threaten Central Banks: The IMF's Stablecoin Warning","digital-dollars-threat-central-banks-imf-stablecoin-warning"],
  ["Why 2026's Tokenization Boom Could Turn the Tide on This Market Dip","2026-tokenization-boom-market-dip"],
  ["Why Bitcoin Briefly Hit $73K This Week — And What Happens Next","bitcoin-hit-73k-what-happens-next"]
].map(([title, slug]) => ({ title, url: slug ? `https://www.lbank.com/creator/${slug}` : 'https://www.lbank.com/creator' }));
